services:
  moneygate:
    image: moneygate
    build:
      context: .
      dockerfile: MoneyGate/Dockerfile
    ports:
      - "4101:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'moneygate'
      POSTGRES_PASSWORD: 'moneygate'
      POSTGRES_DB: 'moneygateDb'
